/*
 * This source file was generated by the Gradle 'init' task
 */
package bibliometry

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = bibliometry.App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
