/*
 * This source file was generated by the Gradle 'init' task
 */
package bibliometry
class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(bibliometry.App().greeting)

}

